version: "3.8"

services:
  mysql:
    image: mysql:8.0.25
    container_name: rentacar-mysql
    ports:
      - "13306:3306"
    environment:
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=rent-a-car
    volumes:
      - ./mysql-data:/var/lib/mysql